version: 2

formats:
  - pdf

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - extra
        - docs

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - gfortran

sphinx:
  fail_on_warning: false