!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitspecpart(f2pysetupfunc)
      use specpart, only : ihmax
      use specpart, only : partition
      external f2pysetupfunc
      call f2pysetupfunc(ihmax,partition)
      end subroutine f2pyinitspecpart


