name: Codecov

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    -
        name: Checkout code
        uses: actions/checkout@v4
    -
        name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
    -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . 'wavespectra[extra,test]'
    -
        name: Run tests
        run: |
          coverage run -m pytest
          coverage xml
    -
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
